# Generated by Django 4.2.29 on 2026-04-01 00:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('messages', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['-updated_at'], name='chats_updated_at_desc')],
            },
        ),
    ]
